//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newsApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificationID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Type { get; set; }
        public string Message { get; set; }
        public Nullable<bool> Is_Read { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
    
        public virtual User User { get; set; }
    }
}
