//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newsApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableConfig
    {
        public int TableConfigId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> TableConfigMostLiked { get; set; }
        public Nullable<int> TableConfigMostRead { get; set; }
        public Nullable<int> TableConfigMostTagged { get; set; }
        public Nullable<int> TableConfigFavoriteCategory { get; set; }
    
        public virtual User User { get; set; }
    }
}
